# Part I: This Notebook provides Python code snippets that exercise matrix properties: matrix addition, scalar multiplication, matrix multiplication, and the identity matrix.
## This will utilize NumPy to handle matrix operations effectively

In [23]:
import numpy as np

## Define matrices A and B for testing

In [24]:
# Matrix can be created by np.array()
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(A)
print()
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [29]:
## Shape of matrices A and B

In [30]:
A.shape

(3, 3)

In [31]:
B.shape

(3, 3)

Both matrices have 3 raws and 3 columns

## Sum of two matrices (A + B)

In [11]:
C_sum = A + B
print("Matrix Addition (A + B):\n", C_sum)

Matrix Addition (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


## Difference of two matrices (A - B)

In [12]:
C_diff = A - B
print("Matrix Difference (A - B):\n", C_diff)

Matrix Difference (A - B):
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


## Scalar multiplication (λ * A)

In [13]:
λ = 2
C_scalar = λ * A
print(f"Scalar Multiplication ({λ} * A):\n", C_scalar)

Scalar Multiplication (2 * A):
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Matrix multiplication (A * B)
### Note: Matrix multiplication requires A and B to have compatible dimensions

In [14]:
C_product = np.dot(A, B)
print("Matrix Multiplication (A * B):\n", C_product)

Matrix Multiplication (A * B):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## Properties of matrix multiplication
### (A + B) * C == A * C + B * C
### We define a new matrix C to validate this property.

In [16]:
C = np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]])
left_side = np.dot(A + B, C)
right_side = np.dot(A, C) + np.dot(B, C)
print("Validation of (A + B) * C = A * C + B * C:\n", left_side == right_side)

Validation of (A + B) * C = A * C + B * C:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Identity matrix multiplication
### Define identity matrix E of same size as A

In [19]:
E = np.identity(3)
E_A = np.dot(E, A)
A_E = np.dot(A, E)
print("Identity Matrix (E):\n", E)
print("\nE * A = A:\n", E_A)
print("\nA * E = A:\n", A_E)
print("\nValidation of E * A = A * E:\n", E_A == A_E)

Identity Matrix (E):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

E * A = A:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

A * E = A:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Validation of E * A = A * E:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
