# Part 2: This Notebook provides Python code snippets that exercise the matrix DETERMINANT properties.

## This will utilize NumPy to handle matrix operations effectively

In [1]:
import numpy as np

# 1. Helping function to display a matrix for better readability and calculate determinant manually

In [3]:
def display_matrix(title, matrix):
    print(f"{title}:\n{np.array(matrix)}\n")

def determinant_manual(matrix):
    # Unpack elements
    a1, b1, c1 = matrix[0]
    a2, b2, c2 = matrix[1]
    a3, b3, c3 = matrix[2]

    return (
        a1 * b2 * c3 +
        b1 * c2 * a3 +
        c1 * a2 * b3 -
        c1 * b2 * a3 -
        b1 * a2 * c3 -
        a1 * c2 * b3
    )

## Initial matrix

In [5]:
A = np.array([
    [2, 1, 2],
    [3, 3, 5],
    [1, 0, 1]
])

display_matrix("Original Matrix A", A)

Original Matrix A:
[[2 1 2]
 [3 3 5]
 [1 0 1]]



## Calculate determinant manually and compare with NumPy's built-in function

In [7]:
# Manually calculated determinant
print("Manual Determinant using formula (2):", determinant_manual(A))

# Use NumPy's built-in function
print("NumPy Determinant:", round(np.linalg.det(A)))


Manual Determinant using formula (2): 2
NumPy Determinant: 2


# 2. Properties of determinant

## Property 1: Transpose does not change determinant

In [8]:
print("\nProperty 1: det(A) = det(A.T)")
print("det(A):", round(np.linalg.det(A)))
print("det(A.T):", round(np.linalg.det(A.T)))



Property 1: det(A) = det(A.T)
det(A): 2
det(A.T): 2


## Property 2: Swapping rows/columns multiplies determinant by -1

In [9]:
B = A.copy()
B[[0, 1]] = B[[1, 0]]  # Swap first and second rows
print("\nProperty 2: Row swap changes sign")
print("Original det(A):", round(np.linalg.det(A)))
print("Swapped rows det(B):", round(np.linalg.det(B)), "Expected:", -round(np.linalg.det(A)))



Property 2: Row swap changes sign
Original det(A): 2
Swapped rows det(B): -2 Expected: -2


## Property 3: Duplicate rows or columns → det = 0

In [10]:
C = np.array([
    [2, 2, 7],
    [3, 3, 5],
    [4, 4, 1]
])
print("\nProperty 3: Duplicate columns → det = 0")
print("Matrix:\n", C)
print("Determinant:", round(np.linalg.det(C)))



Property 3: Duplicate columns → det = 0
Matrix:
 [[2 2 7]
 [3 3 5]
 [4 4 1]]
Determinant: 0


## Property 4: Scalar multiple of a row/column scales det

In [11]:
λ = 5
D = A.copy()
D[:, 0] = λ * D[:, 0]  # Multiply first column by λ
print(f"\nProperty 4: Multiply column by λ={λ}")
print("det(λ*A_column):", round(np.linalg.det(D)))
print("λ * det(A):", round(λ * np.linalg.det(A)))



Property 4: Multiply column by λ=5
det(λ*A_column): 10
λ * det(A): 10


## Property 5: Zero row or column → det = 0

In [12]:
E = np.array([
    [0, 1, 2],
    [0, 3, 5],
    [0, 0, 1]
])
print("\nProperty 5: Zero column → det = 0")
print("Determinant:", round(np.linalg.det(E)))



Property 5: Zero column → det = 0
Determinant: 0


## Property 6: Proportional rows/columns → det = 0

In [13]:
F = np.array([
    [2, 4, 7],
    [3, 6, 5],
    [4, 8, 1]
])
print("\nProperty 6: Proportional columns → det = 0")
print("Determinant:", round(np.linalg.det(F)))



Property 6: Proportional columns → det = 0
Determinant: 0


## Property 7: Column/row sum split

In [22]:
A_prime = np.array([
    [1, 1, 2],
    [1, 3, 5],
    [1, 0, 1]
])
A_double_prime = np.array([
    [1, 1, 2],
    [2, 3, 5],
    [0, 0, 1]
])
# for example: Sum in the first column only.
G = np.array([
    [1 + 1, 1, 2],
    [1 + 2, 3, 5],
    [1 + 0, 0, 1]
])
print("\nProperty 7: Splitting column into two parts")
print("det(A' + A''):", round(np.linalg.det(G)))
print("det(A') + det(A''):", round(np.linalg.det(A_prime)) + round(np.linalg.det(A_double_prime)))


Property 7: Splitting column into two parts
det(A' + A''): 2
det(A') + det(A''): 2


## Property 8: Adding λ × row to another does not change det

In [15]:
λ = 2
H = A.copy()
H[:, 0] = H[:, 0] + λ * H[:, 1]
print(f"\nProperty 8: Add λ*col2 to col1 (λ={λ})")
print("New det:", round(np.linalg.det(H)))
print("Original det:", round(np.linalg.det(A)))


Property 8: Add λ*col2 to col1 (λ=2)
New det: 2
Original det: 2


## Property 9: Cofactor expansion

In [16]:
def minor(matrix, i, j):
    sub_matrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    return round(np.linalg.det(sub_matrix))

def cofactor_expansion(matrix, row=0):
    cofactors = []
    for j in range(3):
        sign = (-1) ** (row + j)
        minor_det = minor(matrix, row, j)
        cofactors.append(sign * matrix[row][j] * minor_det)
    return sum(cofactors)

print("\nProperty 9: Expansion along the first row (cofactor)")
print("Cofactor expansion result:", cofactor_expansion(A))
print("Numpy det:", round(np.linalg.det(A)))


Property 9: Expansion along the first row (cofactor)
Cofactor expansion result: 2
Numpy det: 2


## Property 10: Cross cofactor expansion = 0

In [18]:
# Sum of elements of col2 with cofactors of col1
cofactor_1 = [
    (-1)**(0+0) * minor(A, 0, 0),
    (-1)**(1+0) * minor(A, 1, 0),
    (-1)**(2+0) * minor(A, 2, 0)
]
sum_cross = A[0][1]*cofactor_1[0] + A[1][1]*cofactor_1[1] + A[2][1]*cofactor_1[2]
print("\nProperty 10: Cross-column expansion → should be 0")
print("Result:", sum_cross)


Property 10: Cross-column expansion → should be 0
Result: 0
